### ISSUE TITLE
2.0.0-alpha.29 update

### ISSUE THREAD

**Issue by NathanWalker** [auth0/angular2-authentication-sample#22]
Not 100% sure, but I cannot get this repo to work with the latest 2.0.0-alpha.29. I can't get 'Router' injected, `error TS2304: Cannot find name 'Router'`

**Comment by mgonto** [comment]
Somebody is working on updating it and will send a PR soon.

**Comment by PatrickJS** [comment]
fixed via https://github.com/auth0/angular2-authentication-sample/pull/24
